# Stage 1: Build
FROM node:18 AS builder
WORKDIR /app

COPY package*.json ./
RUN npm install --include=dev

COPY . .
RUN npm run build   # จะสร้าง dist/ 

# Stage 2: Production
FROM node:18 AS runner
WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev  # ติดตั้งเฉพาะ dependencies

COPY --from=builder /app/dist ./dist

CMD ["node", "dist/index.js"]
